# https://gohugo.io/getting-started/configuration/
baseURL = "https://education.launchcode.org/gis-devops"
languageCode = "en-us"
title = "GIS-DevOps"
theme = ["learn"] 

ignoreFiles = [ "\\.stub$" ]

[outputs]
# HTML: site
# RSS: feed data
# JSON: search indexing
home = [ "HTML", "RSS", "JSON"]

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
themeVariant = "blue"
custom_css = ["css/technical-training.css"]
disableInlineCopyToClipBoard = true
disableLandingPage = false
showVisitedLinks = true
# sets the "edit this page" base URL
# !! must include branch name and end with src/ for proper pathing !!
editURL = "https://github.com/LaunchCodeEducation/gis-devops/tree/master/src/"
disableNextPrev = true

[Languages]
[Languages.en]
landingPageURL = "/gis-devops"
landingPageName = "<i class='fas fa-home'></i> Course Schedule"
# -- sidebar --

# [[menu.shortcuts]] 
# identifier = "github"
# name = "<i class='fab fa-github'></i> Github repo"
# url = "https://github.com/launchcodeeducation/gis-devops"
# weight = 10